myapp/urls.py
from django.urls import re_path #import url was broken
from . import views
from django.urls import path
from django.conf.urls import include

app_name = 'diary'

urlpatterns = [
    path('',views.index_template, name='index')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),
]

myapp/models.py
from django.db import models

# Create your models here.

myapp/views.py
from django.shortcuts import render
from django.http.response import HttpResponse

def index_template(request):
    return render(request, 'index.html')

templates/base.html
{%load static%}

<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock %}</title>

        <link href "{% static 'vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
        
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet" />
        
        <link href = "{% static 'css/one-page-wonder.min.css'%}" rel="stylesheet">
        
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href= "{% static 'css/mystyle.css'%}" />
        {% block head %}{% endblock %}
    </head>

    <body>
        <div id="wrapper">
            <!-- Navigation-->
            <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
                <div class="container px-5">
                    <a class="navbar-brand" href="{% url 'diary:index' %}">PRIVATE DIARY</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navbarResponsive">
                        <ul class="navbar-nav ms-auto">
                            <li class="nav-item"{% block active_inquiry %}{% endblock %}><a class="nav-link" href="#!"></a>INQUIRY</li>
                            <li class="nav-item"><a class="nav-link" href="#!">Log In</a></li>
                        </ul>
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class = "nav-link" href="#">SignUp</a>
                            </li>
                            <li class="nav-item">
                                <a class = "nav-link" href="#">Log In</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>

            {% block header %}{% endblock %}

            {% block contents %}{% endblock %}
            
            <!-- Footer-->
            <footer class="py-5 bg-black">
                <div class="container px-5"><p class="m-0 text-center text-white small">Copyright &copy; Private Dairy</p></div>
            </footer>
            <!-- Bootstrap core JS-->
            <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
            <!-- Core theme JS-->
            <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    </body>
</html>

templates/index.html
{%load static%}

<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock %}</title>

        <link href "{% static 'vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
        
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet" />
        
        <link href = "{% static 'css/one-page-wonder.min.css'%}" rel="stylesheet">
        
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href= "{% static 'css/mystyle.css'%}" />
        {% block head %}{% endblock %}
    </head>

    <body>
        <div id="wrapper">
            <!-- Navigation-->
            <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
                <div class="container px-5">
                    <a class="navbar-brand" href="{% url 'diary:index' %}">PRIVATE DIARY</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navbarResponsive">
                        <ul class="navbar-nav ms-auto">
                            <li class="nav-item"{% block active_inquiry %}{% endblock %}><a class="nav-link" href="#!"></a>INQUIRY</li>
                            <li class="nav-item"><a class="nav-link" href="#!">Log In</a></li>
                        </ul>
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class = "nav-link" href="#">SignUp</a>
                            </li>
                            <li class="nav-item">
                                <a class = "nav-link" href="#">Log In</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>

            {% block header %}{% endblock %}

            {% block contents %}{% endblock %}
            
            <!-- Footer-->
            <footer class="py-5 bg-black">
                <div class="container px-5"><p class="m-0 text-center text-white small">Copyright &copy; Private Dairy</p></div>
            </footer>
            <!-- Bootstrap core JS-->
            <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
            <!-- Core theme JS-->
            <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    </body>
</html>